name: advent-of-code-2k20
version: 0.1.0.0
github: "gipphe/advent-of-code-2k20"
license: BSD3
author: "Victor Nascimento Bakke"
copyright: "2020 Victor Nascimento Bakke"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/gipphe/advent-of-code-2k20#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - deepseq
  - file-embed
  - hashable
  - megaparsec
  - parser-combinators
  - time
  - vector

ghc-options:
  # Warnings and safety
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wunused-binds
  - -Wunused-imports
  - -Wunused-foralls
  - -Wpartial-fields
  - -Wredundant-constraints
  - -flate-specialise
  - -fspecialise-aggressively

library:
  source-dirs: src

executables:
  advent-of-code-2k20-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent-of-code-2k20

tests:
  advent-of-code-2k20-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent-of-code-2k20
      - tasty
      - tasty-hunit
      - tasty-discover

benchmarks:
  advent-of-code-2k20-profile:
    main: Profile.hs
    source-dirs: profile
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent-of-code-2k20
